### ISSUE TITLE
No ingredients folder on fresh install

### ISSUE THREAD

**Issue by nik-418** [joecohens/laravel-elixir-requirejs#1]
@joecohens :)

```
Error: Cannot find module 'laravel-elixir/ingredients/helpers/utilities'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Nikita/Code/cs/node_modules/laravel-elixir-requirejs/index.js:8:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by joecohens** [comment]
I've just updated it to the last version of elixir. Let me know if everything ok :). See https://github.com/joecohens/laravel-elixir-requirejs/commit/2f362dcd18f5ca4e5f42f6540fd47d4552cc5088

**Comment by nik-418** [comment]
Cheers, now another bug: "gulpif" line 3 vs "gulpIf" line 30 :)

**Comment by nik-418** [comment]
Made a pull request: https://github.com/joecohens/laravel-elixir-requirejs/pull/2
