### ISSUE TITLE
Error: Cannot find module 'underscore'

### ISSUE THREAD

**Issue by guoyunhe** [joecohens/laravel-elixir-requirejs#14]
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/tom/git/myproject/node_modules/laravel-elixir-requirejs/index.js:3:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Maybe here is a problem on dependency or module loading?

**Comment by guoyunhe** [comment]
Found the problem. Underscore is set as devDependency but should be a runtime dependency.

**Comment by kel** [comment]
I am having the same issue.
