### ISSUE TITLE
Incompatible with Elixir 3.0

### ISSUE THREAD

**Issue by thomaswelton** [joecohens/laravel-elixir-requirejs#3]
```
Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/redacted/node_modules/laravel-elixir-requirejs/index.js:7:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

```

**Comment by joecohens** [comment]
Can you help me confirm v0.1.0 is working with Elixir 3? Thanks!

**Comment by thomaswelton** [comment]
v0.1.0 doesn't work see #5

**Comment by thomaswelton** [comment]
@joecohens bump

**Comment by joecohens** [comment]
Done :)
