### ISSUE TITLE
mix.requirejs is not a function

### ISSUE THREAD

**Issue by sjaved193** [joecohens/laravel-elixir-requirejs#7]
Hi, 
Whenever I run gulp in my terminal I always get following error. 

vagrant@homestead:~/Code/proj-code$ gulp --production
/home/vagrant/Code/proj-code/gulpfile.js:43
    mix.requirejs('scripts.js', rjsOptions).version([
        ^

TypeError: mix.requirejs is not a function
    at /home/vagrant/Code/proj-code/gulpfile.js:43:9
    at Elixir (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/index.js:16:5)
    at Object.<anonymous> (/home/vagrant/Code/proj-code/gulpfile.js:26:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)

I have installed this package as required and even manually copy pasted all files but I am always getting this error.

**Comment by Freid001** [comment]
@joecohens bump

**Comment by joecohens** [comment]
Please upgrade to v1.0.0. Everything should be fixed now. Let me know if you find bugs :)

**Comment by babyplanet** [comment]
When I have changed to v1.0.0 the error gone and now getting new one. :( 
/home/vagrant/Code/proj-code/node_modules/laravel-elixir/node_modules/parse-filepath/index.js:8
    throw new Error('parse-filepath expects a string.');
    ^

Error: parse-filepath expects a string.
    at parse (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/node_modules/parse-filepath/index.js:8:11)
    at GulpPaths.parse (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/GulpPaths.js:130:20)
    at GulpPaths.output (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/GulpPaths.js:53:24)
    at prepGulpPaths (/home/vagrant/Code/proj-code/node_modules/laravel-elixir-requirejs/index.js:49:10)
    at Function.<anonymous> (/home/vagrant/Code/proj-code/node_modules/laravel-elixir-requirejs/index.js:10:17)
    at Function.<anonymous> (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/index.js:40:18)
    at /home/vagrant/Code/lawcus-code/gulpfile.js:43:9
    at Elixir (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/index.js:16:5)
    at Object.<anonymous> (/home/vagrant/Code/proj-code/gulpfile.js:26:1)
    at Module._compile (module.js:434:26)

**Comment by babyplanet** [comment]
@joecohens bump

**Comment by sjaved193** [comment]
When I have changed to v1.0.0 the error gone and now getting new one. :( 

/home/vagrant/Code/proj-code/node_modules/laravel-elixir/node_modules/parse-filepath/index.js:8
throw new Error('parse-filepath expects a string.');
^

Error: parse-filepath expects a string.
at parse (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/node_modules/parse-filepath/index.js:8:11)
at GulpPaths.parse (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/GulpPaths.js:130:20)
at GulpPaths.output (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/GulpPaths.js:53:24)
at prepGulpPaths (/home/vagrant/Code/proj-code/node_modules/laravel-elixir-requirejs/index.js:49:10)
at Function. (/home/vagrant/Code/proj-code/node_modules/laravel-elixir-requirejs/index.js:10:17)
at Function. (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/index.js:40:18)
at /home/vagrant/Code/lawcus-code/gulpfile.js:43:9
at Elixir (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/index.js:16:5)
at Object. (/home/vagrant/Code/proj-code/gulpfile.js:26:1)
at Module._compile (module.js:434:26)

**Comment by sjaved193** [comment]
@joecohens bump

**Comment by sjaved193** [comment]
Which version of elixir would be compatible with which version of requirejs? Currently, I am using
`"laravel-elixir": "*"`
`"laravel-elixir-requirejs": "1.0.0",`

**Comment by joecohens** [comment]
Please use `"laravel-elixir": "^4.0.0"  you don't need to install requirejs since laravel-elixir-requirejs installs it automatically. Let me know :)

**Comment by sjaved193** [comment]
Hi @joecohens , I have upgraded to "laravel-elixir": "^4.0.0", as per your directions:

So now either I remove require('laravel-elixir-requirejs'); from my gulpfile.js or not I got again the first error

/home/vagrant/Code/proj-code/gulpfile.js:43
    mix.requirejs('scripts.js', rjsOptions).version([
        ^

TypeError: mix.requirejs is not a function
    at /home/vagrant/Code/proj-code/gulpfile.js:43:9
    at Elixir (/home/vagrant/Code/proj-code/node_modules/laravel-elixir/index.js:16:5)
    at Object.<anonymous> (/home/vagrant/Code/proj-code/gulpfile.js:26:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)

Happy first error again :)

**Comment by joecohens** [comment]
Can you post me your gulpfile.js please?

**Comment by sjaved193** [comment]
var elixir = require('laravel-elixir');
var should = require('should');

// Load additional tasks
require('laravel-elixir-requirejs');
require('laravel-elixir-mocha');

// Configure elixir
elixir.config.assetsPath = 'public/assets';

// require.js options
var rjsOptions ={
    baseUrl: 'public/assets/js',
    out: 'scripts.js',
    mainConfigFile : 'public/assets/js/scripts.js',
    name: 'scripts',
    include: ['require.js'],
    optimize: 'uglify',
    removeCombined: true,
    findNestedDependencies: true
};

// styles options
var cssPaths = 'public/assets/css';

elixir(function(mix) {
    mix.styles([
        'jquery-ui.css',
        'calendar/fullcalendar.css',
        'layout.css',
        'styles.css',
        'responsive.css',
        'chosen.css',
        'sweetalert.css',
        'bootstrap.css',
        'font-icons.css',
        'timepicker.css',
        'toastr.css', 
        'jquery.atwho.css'
    ],  'public/assets/css/everything.css', cssPaths);

```
mix.requirejs('scripts.js', rjsOptions).version([
    'assets/css/everything.css',
    'js/scripts.js'
]);    
mix.mocha([
  'tests/api/**/*.spec.js'
], {
    globals: [should],
    timeout: 100000
});
```

});

Either I comment out require('laravel-elixir-requirejs') or not, error persist.

**Comment by joecohens** [comment]
Ok I've switched the api options with output, I think it makes more sense. Please upgrade to v1.1.0 and your rjsOptions can be like this:

```
// require.js options
var rjsOptions = {
    mainConfigFile : 'public/assets/js/scripts.js',
    include: ['require.js'],
    optimize: 'uglify',
    removeCombined: true,
};
```

Since we are already defining the other options out of the box, and they will be merge with your own.

https://github.com/joecohens/laravel-elixir-requirejs/blob/master/index.js#L12

Let me know if everything is working now :) Thanks!
